### ISSUE TITLE
ШАГ 2. Артур Цой (@artwebcode)

### ISSUE THREAD

**Issue by artwebcode** [RYAZHAPOVILNUR/mentoring-users-app#243]
ШАГ 2. Артур Цой (@artwebcode)

Сделал задачи с 1-16. 
Процесс занял около 2 недель, так как были перерывы. А так в целом по времени потребовалось около 20 часов
Дополнительно делал:
- верстка по дизайну
- внутренние страницы пользователя

Репа: https://gitlab.com/ArtTS/angular-users/

Мне интересно узнать:
1. качество кода. Мне кажется что нагавнокодел. Думаю много где можно сделать лучше.
2. Была проблема с добавлением пользователя.
До попапа все работа корректно. После добавление пользователя через попап, у меня постоянно пользователи добавляются с ID равному 11. Не понял в чем причина. Сделал костыль, переписываю ему ID

Скриншот: https://disk.yandex.ru/i/BDlQD63jeM0g7Q

**Comment by RYAZHAPOVILNUR** [comment]
ПРИНЯТО, теперь на ngrx
