### ISSUE TITLE
ШАГ 2, Артем, https://t.me/ArtKanareyka

### ISSUE THREAD

**Issue by ArtKanareyka** [RYAZHAPOVILNUR/mentoring-users-app#246]
https://github.com/ArtKanareyka/my-first-project
Решил до 16 задания пока что.
Решение заняло примерно 4 недели, грязными. На выходных отдыхал и в некоторые дни недели работал. Примерно чистыми дней 20. 
Сильно втупил на формах, не мог понять как сделать "глупым" компонент разбирался дней 5-6. 
3 дня разбирался с localStorage, оказалось всё просто.

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/b12b9562-6010-4aba-acdd-1ec741d57b1f)

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/bfcfaeb5-79db-48a5-903b-cd8e9893e3c3)

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/69c8831b-d4fd-4731-a1be-017f0d423267)

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/2635ec48-b258-4eef-973e-4353f8a2b339)

**Comment by krymnon69** [comment]
какой смысл пихать их в отдельные папки?
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/674bf01f-7b52-4367-a719-4a722f6acf4d)

**Comment by krymnon69** [comment]
`this.api.get().subscribe((response: IUser[]) => `
1. вечно живущая подписка
2. код в subscribe
3. api, get - выглядит странно. непонятно какой гет у какого api. так вылядело бы нагляднее:
this.userApiService.getUsers()

**Comment by krymnon69** [comment]
сам подумай:
```
this.usersSubject$.subscribe((response: IUser[]) => {
   response.splice(
      response.findIndex(user => user.id === id),
      1
)
```
ты в подписке на значение потока мутируешь значение этого потока
ни в коем случае нельзя так делать

**Comment by krymnon69** [comment]
```
		this.usersSubject$.subscribe((response: IUser[]) => {
			userFormData.id = response.length + 1
			response.push(userFormData)
			this.localStorageService.setItem(response)
		})
```
аналогично. надругательство над сабджектом

**Comment by krymnon69** [comment]
@Input({ required: true }) user: IUser | undefined
	если required: true то значит уже точно не undefined)

**Comment by krymnon69** [comment]
что то с типами. они не верные
`@Output() deleteUserEvent = new EventEmitter<number | undefined>()`

**Comment by krymnon69** [comment]
`LocalStorageService {
	getItem() {
		return localStorage.getItem('usersList')
	}`
	"универсальный" localStorage сервис получает только данные по ключу "usersList". печально. мог бы получать этот ключ из вне (продумай также и для setItem, дата также должна быть не обязательна типа IUser[])

**Comment by krymnon69** [comment]
попробуй через InjectionToken (найдёшь примеры в чатике)
`private readonly apiUsersUrl = environment.apiUsersUrl`

**Comment by krymnon69** [comment]
`public readonly users$: Observable<IUser[]> = this.usersSubject$.asObservable()`
Observable<IUser[]> = излишний тип

**Comment by krymnon69** [comment]
НА ДОРАБОТКУ
