### ISSUE TITLE
ШАГ 2. Нурмухаммад Тасуев (@sonomad1) ДОРАБОТАЛ

### ISSUE THREAD

**Issue by SoNomad** [RYAZHAPOVILNUR/mentoring-users-app#250]
ШАГ 2. Нурмухаммад Тасуев (@sonomad1)

Сделал задачи с 1-16.
Заняло 3-4 ночи (днем работа).  Изначально делал все с одним сервисом, используя потоки rxjs, потом в пунктах задания заметил, что этого не требовалось и убрал.

Трудности: 
Тупняки с диалоговым окном, долго догонял как запихнуть данные редактируемого юзера в инпуты. Не уверен в чистоте кода, возможно много костылей. 
В процессе внедрения ngrx.

Репа: https://github.com/SoNomad/mentoring

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/5ecb519f-db0d-432f-86ce-06ad81cb7e68)

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/3c0ede74-aa18-4220-bc43-3fad43a05264)

**Comment by krymnon69** [comment]
MatDialogComponent -> CreateEditUserModalComponent

**Comment by krymnon69** [comment]
public userFormGroup = new FormGroup
вынеси в сервис, захломляется файл .ts

**Comment by krymnon69** [comment]
по факту не нужна, поищи по поиску в чате:
  public readonly isEditable: boolean = !!this.data;

**Comment by krymnon69** [comment]
@Output() public deleteUserId: EventEmitter<number> = new EventEmitter();
  @Output() public editableUser: EventEmitter<User> = new EventEmitter();
  
  EventEmitter<number> и  EventEmitter<User> тоже излишние типы
  их лучше задать после знака равно: new EventEmitter<User>();

**Comment by krymnon69** [comment]
deleteUserHandler => onDeleteUserClick()

**Comment by krymnon69** [comment]
idGenerator.ts => id-generator.util.ts

**Comment by krymnon69** [comment]
НА ДОРАБОТКУ!

**Comment by SoNomad** [comment]
> НА ДОРАБОТКУ!

Доработал

**Comment by krymnon69** [comment]
@Input() public user!: User;
  @Output() public deleteUserId = new EventEmitter<number>();
  @Output() public editableUser = new EventEmitter<User>();
  
1.   user - может быть undefined, не стоит глушить TS с помощью "!"
  почитай по поиску в чате про @Input({ required: true })
  2. deleteUserId, editableUser - почему то публичные и не readonly

**Comment by krymnon69** [comment]
накидывать formGroupName не несёт никакого смысла, т.к. на родителя у тебя уже повешен [formGroup]:
```
  <mat-form-field formGroupName="address" class="example-full-width">
    <mat-label>city</mat-label>
    <input matInput formControlName="city" placeholder="Enter city" />
  </mat-form-field>
```

**Comment by krymnon69** [comment]
@Inject(MAT_DIALOG_DATA) public data: User
почему то публичное и не readonly

**Comment by krymnon69** [comment]
как в сервисе оказалась форма?
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/65f628c1-e8e6-41c3-b546-ae1a221c5d3b)
в данном случае этот файл можно назвать user-form.helper.ts
и положить сответственно по пути users/helpers/**.ts

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/4d69963c-bc02-47cd-a5f4-533d0ac618a9)

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/f7143da0-41fe-4d27-9b8b-9bdcfd749455)

**Comment by krymnon69** [comment]
очень странная и непонятная история, от этого следует избавиться:
export function dialogConfigure(user?: User, height?: string, width?: string) {
  return {
    height: height || '550px',
    width: width || '450px',
    data: user,
  };
}

если нужно сохранять где то настройки, то они будут лежать в константе (конфиге) всего приложения

**Comment by krymnon69** [comment]
public userFormGroup = userFormGroup(this.data);
  методы называются с глагола, т.е. getUserForm()

**Comment by krymnon69** [comment]
файл user-modal имеет в себе класс CreateEditUserModalComponent
а нужно называть файлы по имени сущности которая в них лежит

**Comment by krymnon69** [comment]
User.ts => user.type.ts

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/3af5b406-6d27-46f7-b301-31a198d38cd7)

**Comment by krymnon69** [comment]
Замечания учти для себя и газуй дальше)
