### ISSUE TITLE
ШАГ 2 Кайрат @kairat_asylbekov

### ISSUE THREAD

**Issue by asylbekovkairat** [RYAZHAPOVILNUR/mentoring-users-app#252]
https://github.com/asylbekovkairat/users-app-junior

задачу сделал во второй раз, чтобы освежить память по ангуляру и укрепить знания. справился с задачей чистыми за 4 часа,

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/8d7004e3-0e99-44b0-8c32-1085ca5f2d56)

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/39f4dc1a-63cf-4386-a510-d6ed93bd000c)

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/ab2df7ad-38f6-45f9-ab1b-663ab00563e1)

**Comment by krymnon69** [comment]
`export class LocaleStorageService {
  constructor() {}

  getUsers(): IUser[] | undefined {
    const users = localStorage.getItem('users');
    if (typeof users === 'string') return JSON.parse(users);
    else return undefined;
  }`
  сервис не универсален и получает данные только по ключу users

**Comment by krymnon69** [comment]
const userAPIService = inject(UsersApiService);
почему вдруг API

**Comment by krymnon69** [comment]
export type LoadingStatus = 'init' | 'loading' | 'success' | 'error';
тот же статус error можно определить по наличию поля error в стейте
init - тоже неуместно, но бывает
