### ISSUE TITLE
ШАГ 1 {{Литвиненко Роман}} {{@Alucard163}}

### ISSUE THREAD

**Issue by Alucard163** [RYAZHAPOVILNUR/mentoring-users-app#258]
Переписал джун задание на ngrx https://github.com/Alucard163/typicode-users-angular-app

**Comment by krymnon69** [comment]
(click)="userForm.valid ? onDialogCloseClick(userForm.value) : null"
лучше просто задизейблить кнопку, либо делать уже в самом методе: 
if(userForm.invalid) return;

**Comment by krymnon69** [comment]
this.userForm = this.formBuilder.group({
лучше проинициализировать сразу, чем писать в конструкторе

**Comment by krymnon69** [comment]
this.user?.name || ''
вместо этого легче один раз сделать this.userForm.patchValue()

**Comment by krymnon69** [comment]
this.userForm.controls[field]
убиваешь типы (обращение через [''] возвращает тип any)
для форм придумали userForm.get()

**Comment by krymnon69** [comment]
@Output('delete') deleteCard 
кажется устаревшая и не лучшая практика присваивать другое имя событию (delete)

**Comment by krymnon69** [comment]
public usersListFacade = inject(UsersListFacade);
  public users$ = this.usersListFacade.users$;
  
  это тоже может быть readonly
  и users$ может вообще не быть, можно обратиться сразу к usersListFacade.users$

**Comment by krymnon69** [comment]
data-access относится к архитектуре nx

**Comment by krymnon69** [comment]
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/113257050/24bc4c58-04e0-4083-81a3-fb787637cf9a)

**Comment by krymnon69** [comment]
методы в UsersApiService можно назвать без постфикса Users, т.к. они априори относятся к объекту USERSApiService

**Comment by krymnon69** [comment]
private parseJSON = parseJSON;
  это лишнее (переменная)

**Comment by krymnon69** [comment]
shared должен быть один по всему приложению на верхнем уровне (уровне app.comp)

**Comment by krymnon69** [comment]
некорректное название файла localStorageHelpers.ts

**Comment by krymnon69** [comment]
было бы круто если бы локал сторадж сервис сам занимался парсингом и стрингифаем данных

**Comment by krymnon69** [comment]
export const LOCAL_STORAGE_USERS_KEY = 'users';
лучше делать enum:
```
export enum StorageKey = {
   USERS = 'users'
}
```

**Comment by krymnon69** [comment]
Из-за того что ты делаешь нереальную в реальной жизни задачу - синхронизируешь ngrx с localstorage - много говнокода и DRY с этим связанного. Советую избавиться от синхронизации со storage, учесть замечания но больше для себя. Пишешь не плохо, я считаю стоит поправить для себя, быстро на дейлике пробежимся глазами и пойдёшь дальше.
ПРИНЯТО
