### ISSUE TITLE
Добавить редактирование юзера в профиле

### ISSUE THREAD

**Issue by RYAZHAPOVILNUR** [RYAZHAPOVILNUR/mentoring-users-app#58]
Подобный функционал есть на странице /admin/users/72?edit=true

**Comment by 1amarxo** [comment]
Думаю можно убрать отдельно раздел "Профиль" и сделать это по клику по аватарке или в настройках

**Comment by Grayd-WebDev** [comment]
Слегка исправил свой старый код, но попрежнему полноценно имя не меняется. Оно не сохраняется. Нужно сделать запрос на backend с новыми данными. Работаю над этим.

**Comment by Grayd-WebDev** [comment]
В общем у меня проблемка с input-city.component ,

так как он не похож на другие поля я решил сделать чтоб его можно было в любое место вставить и он типа там работает как самостоятельный компонент выдает выборку городов и тд. Тупость в том что input-city  дочерний элемент dialog-profile.component и я его(input-city) импортирую в родительский и там уже где собираются поля обычные: 

  public formGroup = new FormBuilder().group({
    name: new FormControl('', [Validators.required]),
    city: new FormControl("", [Validators.required]),
    email: new FormControl("", [Validators.required, Validators.email])
  });
  
  делаю: 
  
    public onCityReceived (receivedCityControl: any) {
    this.formGroup.addControl("city", receivedCityControl);
  }
  
  эт наверно вообще не правильно =))) 
  подскажите как лучше?))

**Comment by Grayd-WebDev** [comment]
Не могу собрать данные с инпутов и отправить на серв. в консоле ошибка и отдаёт пустые инпуты
