### ISSUE TITLE
Сделать landing page 

### ISSUE THREAD

**Issue by 1amarxo** [RYAZHAPOVILNUR/mentoring-users-app#63]

**Comment by Khkimov** [comment]
- Предлагаю добавить описание школы(проекта).
- Добавить статистику по студентам, с помощью библиотеки highchart.js (pie chart)
например: 
![image](https://github.com/RYAZHAPOVILNUR/mentoring-users-app/assets/85385120/5822d0d3-47ca-4f1d-ad7b-1c52d540549f)
